enable:
  - "attack round transfer"
sets:
  - name: "attack round transfer"
    tests:
      - "check make progress for time out leader"

tests:
  - name: "check make progress for time out leader"
    flow:
      - set_monitor: "miner-1"
      - cleanup_bc: { }
      - start: [ "miner-1", "miner-2", "miner-3", "miner-4" ]
      - start: ["sharder-1"]
      #      - start_lock: ["miner-3"] ## lock Leader_0
      #      - start: [ "miner-1", "miner-2", "miner-4" ]
      - wait_round:
          round: 10
